version: '2.4'
services:
  postgres:
    image: postgres:15.1
    container_name: buy_app_myp3a_db

    ports:
    - 5432:5432

    logging:
      driver: json-file
      options:
        max-size: '100m'
        max-file: '5'

    environment:
      - POSTGRES_DB=buy_app
      - POSTGRES_USER=buy_user
      - POSTGRES_PASSWORD=buy_pass

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  BuyDanBot:
    build:
      context: .

    image: buy_app_myp3a:latest
    container_name: buy_app_myp3a
    hostname: buy_app_myp3a

    ports:
      - 8081:8081

    logging:
      driver: json-file
      options:
        max-size: '100m'
        max-file: '5'

    environment:
      - TELEGRAM_APITOKEN=4242424242:alonglongtokentoauththebot